### ISSUE TITLE
 Replication Issue: Discrepancy in EER

### ISSUE THREAD

**Issue by hungdinhxuan** [ErosRos/conformer-based-classifier-for-anti-spoofing#1]
Hello, @ErosRos 
I am attempting to replicate the results. The paper reports an EER of 2.58, but when I train model myself with the default configurations, I consistently obtain an EER of around 4.5 (e.g., 4.5, 4.56, 4.7 after 3 attempts). 

I would appreciate it if you could help me understand the reasons for the discrepancy in the EER. Any suggestions on how I can improve my replication attempt would be greatly appreciated.

**Comment by ErosRos** [comment]
Hello, @hungdinhxuan,

Thank you for reaching out and for your interest in replicating the results. I've taken a look at your concerns, and I believe the discrepancy could be attributed to the different DA configurations used in the original paper.

In our study (refer to the publication at https://www.isca-speech.org/archive/interspeech_2023/rosello23_interspeech.html), we employed two distinct DA configuration, one for LA and another for DF, and the default configuration in this repository corresponds to the LA configuration. To better align with the reported EER of 2.58, you should adjust the DA technique in your configuration specifically for the DF scenario.

I hope this clarification helps in addressing the discrepancy.
